import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AnswerBox } from "@/components/marketing/answer-box";
import { StructuredData } from "@/components/marketing/structured-data";
import { FinalCTA, GradientSection, SupplierFAQ } from "@/components/marketing/suppliers/shared";
import { absoluteUrl, stages, suppliers } from "@/lib/site-data";

export function generateStaticParams(){return suppliers.map((s)=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params; const s=suppliers.find(x=>x.slug===slug); if(!s)return{}; return{title:`${s.name} | تامین‌کنندگان ساختمانی`,description:s.description,alternates:{canonical:`/suppliers/${s.slug}`},openGraph:{title:s.title,description:s.description,url:absoluteUrl(`/suppliers/${s.slug}`),locale:"fa_IR",type:"article"}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const s=suppliers.find(x=>x.slug===slug); if(!s)notFound(); const related=stages.filter(st=>s.stages.includes(st.name)); const motion=s.description.includes("مشاوره")?"consultative-sales":"fast-sales"; const faqs=[{question:`بهترین زمان تماس برای ${s.name} چه زمانی است؟`,answer:`بهترین زمان، مرحله‌ای است که پروژه به تصمیم خرید ${s.name} نزدیک شده و دسترسی به تصمیم‌گیرنده ممکن باشد.`},{question:"اولویت‌بندی پروژه‌ها چگونه انجام شود؟",answer:"پروژه‌ها را با سه شاخص مرحله ساخت، مقیاس پروژه و کیفیت دسترسی تماس امتیازدهی کنید."},{question:"چگونه پیگیری از دست نرود؟",answer:"برای هر پروژه «گام بعدی» با تاریخ مشخص در CRM ثبت کنید و مسئول روشن داشته باشید."}];
const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"خانه",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:"تامین‌کنندگان",item:absoluteUrl("/suppliers")},{"@type":"ListItem",position:3,name:s.name,item:absoluteUrl(`/suppliers/${s.slug}`)}]};
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
return <main className="mx-auto max-w-7xl space-y-8 px-4 py-10 md:px-6 md:py-16"><StructuredData data={breadcrumb}/><StructuredData data={faqSchema}/><GradientSection><h1 className="text-4xl font-black md:text-6xl">{s.title}</h1><p className="mt-4 leading-8 text-muted-foreground">{s.description}</p><div className="mt-6"><AnswerBox>{s.answer}</AnswerBox></div></GradientSection><GradientSection><h2 className="text-2xl font-black">نمونه محصولات و کاربردها</h2><p className="mt-3 text-muted-foreground">{s.products}</p></GradientSection><GradientSection><h2 className="text-2xl font-black">بینش زمان‌بندی این دسته</h2><p className="mt-3 leading-8 text-muted-foreground">اگر زودتر از موعد وارد شوید هزینه پیگیری بالا می‌رود و اگر دیر برسید احتمال نهایی شدن تامین‌کننده دیگر بالا است.</p></GradientSection><GradientSection><h2 className="text-2xl font-black">پرشین‌سازه چطور کمک می‌کند؟</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{["شناسایی پروژه‌های فعال", "اولویت‌بندی بر اساس مرحله", "ثبت تاریخچه ارتباط", "پیگیری مرحله‌به‌مرحله"].map(t=><div key={t} className="rounded-3xl border bg-white/70 p-4">{t}</div>)}</div></GradientSection><GradientSection><h2 className="text-2xl font-black">مود فروش مرتبط</h2><Link href={`/suppliers/motions/${motion}`}>مشاهده مسیر فروش این دسته</Link></GradientSection><GradientSection><h2 className="text-2xl font-black">مراحل مرتبط</h2><div className="mt-3 flex flex-wrap gap-2">{related.map(r=><Link className="rounded-full border px-3 py-2 text-sm" key={r.slug} href={`/stages/${r.slug}`}>{r.name}</Link>)}</div></GradientSection><SupplierFAQ items={faqs}/><FinalCTA title={`برای رشد فروش ${s.name} آماده‌اید؟`} description="با یک جلسه دمو، پنجره زمانی و مسیر پیگیری اختصاصی همین دسته را طراحی کنید."/></main>}
