import type { Metadata } from "next";
import { AnswerBox } from "@/components/marketing/answer-box";
import { StructuredData } from "@/components/marketing/structured-data";
import { ConstructionStageTimeline, SalesMotionCards, SupplierCategoryFinder, SupplierTimingExplainer, SupplierWorkflow } from "@/components/marketing/suppliers/shared";
import { getConstructionStages, getParentCategories } from "@/lib/supplier-pages-data";

export const metadata: Metadata = { title: "دسته‌بندی تامین‌کنندگان ساختمانی | پرشین‌سازه", description: "سیستم SEO/AEO/GEO برای تامین‌کنندگان ساختمانی", alternates:{canonical:"/suppliers"}, openGraph:{title:"دسته‌بندی تامین‌کنندگان",description:"صفحه مرجع دسته‌های تامین‌کنندگان و زمان‌بندی فروش",url:"https://persiansaze.com/suppliers",locale:"fa_IR"}};

export default function SuppliersPage(){ const categories=getParentCategories(); const stages=getConstructionStages();
const faq=[{"@type":"Question",name:"چطور دسته مناسب را پیدا کنیم؟",acceptedAnswer:{"@type":"Answer",text:"از مثال محصولات و مرحله ساخت شروع کنید."}}];
return <main className="mx-auto max-w-7xl space-y-10 px-4 py-14 md:px-6"><StructuredData data={{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{ "@type":"ListItem", position:1, name:"خانه", item:"https://persiansaze.com"},{"@type":"ListItem",position:2,name:"تامین‌کنندگان",item:"https://persiansaze.com/suppliers"}]}} /><StructuredData data={{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq}} /><section><h1 className="text-4xl font-black">دسته‌بندی تامین‌کنندگان ساختمانی</h1><p className="mt-3 text-muted-foreground">مسیر رشد SEO/AEO/GEO برای فروش پروژه‌محور.</p><div className="mt-4"><AnswerBox>این صفحه به شما کمک می‌کند بر اساس دسته محصول و مرحله ساخت، فرصت مناسب را پیدا و پیگیری کنید.</AnswerBox></div></section><SalesMotionCards items={[{slug:"early-awareness",title:"ورود زودهنگام",text:"قبل از سرد شدن فرصت وارد شوید."},{slug:"timing-based-followup",title:"پیگیری زمان‌محور",text:"تماس را با مرحله خرید هماهنگ کنید."},{slug:"consultative-sales",title:"فروش مشاوره‌ای",text:"با زمینه پروژه مذاکره را پیش ببرید."}]} /><SupplierCategoryFinder categories={categories} /><section><h2 className="text-2xl font-bold">شبکه ۱۷ دسته اصلی</h2></section><SupplierTimingExplainer text="golden timing با ترکیب مرحله ساخت، نوع محصول و کیفیت پیگیری ساخته می‌شود."/><ConstructionStageTimeline stages={stages} /><SupplierWorkflow steps={["مشاهده پروژه‌های فعال روی نقشه","فیلتر بر اساس مرحله ساخت","بررسی جزئیات پروژه","ذخیره فرصت‌های مناسب","تماس یا پیامک هدفمند","ثبت فعالیت در CRM","پیگیری تا زمان مناسب خرید"]} /><section><h2 className="text-2xl font-bold">FAQ</h2></section></main> }
